language: python

python:
  - '2.7'

install:
  - pip install --requirement requirements.txt
  - pip install coveralls

script:
  - coverage run --source="./txes" `which trial` tests/unit && coverage report
  - flake8 .

after_success:
  - coveralls
