language: python

python:
  - '2.7'

install:
  - pip install --requirement requirements/main.txt
  - pip install --requirement requirements/dev.txt
  - pip install coveralls

script:
  - ./bin/unit

after_success:
  - coveralls
